### ISSUE TITLE
Cannot compile plugin

### ISSUE THREAD

**Issue by InfernoBolt** [Sploric/MentionChannels#15]
![image](https://user-images.githubusercontent.com/124555087/216898724-bd393636-bfb5-47be-82f9-98a455084b9b.png)

this mssgs shows everytime i launch bd.

**Comment by Sploric** [comment]
What version of the plugin are you on?

**Comment by wabash1** [comment]
Same issue, 4.2.0+1 from the pluginrepo, I see latest is 5.1.1, any way to update this on the website?

**Comment by ItMeSarah** [comment]
This is still an issue, two different parts of the plugin seem to be broken. 
![image](https://github.com/Setloth/MentionChannels/assets/67713330/50e3e135-8a63-4978-abbb-69c52d0346e4)
![image](https://github.com/Setloth/MentionChannels/assets/67713330/6cb883df-c98d-409e-bd20-f48336e1a5ab)

**Comment by ItMeSarah** [comment]
Scratch that last post, version 5.1.1 fixes it, will see if I can get this sorted to get the correct version on the site.

**Comment by XxUnkn0wnxX** [comment]
@Setloth its dead as off:
```md
## Discord Info
stable 280244 (e5278fb) 

## BetterDiscord
stable 1.10.1
```
<img width="597" alt="Screen Shot 2024-03-31 at 11 17 46 pm" src="https://github.com/Setloth/MentionChannels/assets/2242880/f61bb64f-75f9-4a69-a590-feb5f4a30337">

```
TypeError: Cannot destructure property 'can' of 'getByProps(...)' as it is undefined.
    at eval (betterdiscord://plugins/MentionChannels.plugin.js:29:9)
    at N.requireAddon (betterdiscord/renderer.js:5:28792)
    at N.loadAddon (betterdiscord/renderer.js:5:6412)
    at N.loadAddon (betterdiscord/renderer.js:5:26460)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9469)
    at N.initialize (betterdiscord/renderer.js:5:3284)
    at N.initialize (betterdiscord/renderer.js:5:25573)
    at Object.startup (betterdiscord/renderer.js:5:408848)
    ````

**Comment by XxUnkn0wnxX** [comment]
this ticket can be closed, fixed as of commit: 1d3c9c750bd0164cb9d9503222714f042f6b8c1b

**Comment by XxUnkn0wnxX** [comment]
@Setloth Dead As of: stable 303105 (1897d8a) again

<img width="567" alt="Screen Shot 2024-06-20 at 9 27 48 am" src="https://github.com/Setloth/MentionChannels/assets/2242880/0670b873-1ad7-4278-a896-f0ee1ff5e469">

```
TypeError: Cannot destructure property 'can' of 'getModule(...)' as it is undefined.
    at eval (betterdiscord://plugins/MentionChannels.plugin.js:27:9)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)
    ```
